### PR TITLE
Add Dandelion Sprout's Game Console Ad-block List

### PR DESCRIPTION
**Pull request by cochcoder**
Dandelion Sprout's Game Console Ad-block List contains ad domains that are not in the other lists. The only false positive I have noticed from this list is arc.msn.com. Which is only an issue if you have Game Pass.

### CODE REVIEW

**Comment by sefinek24** [comment]
I think it's better to simply move this file to the folder [blocklist/template/ads](https://github.com/sefinek24/Sefinek-Blocklist-Collection/tree/main/blocklist/template/ads) and delete `arc.msn.com` from it.

To be honest, many blocklists block this subdomain for unknown reasons. Without it, actually receiving the benefits from Microsoft's Game Pass is not possible.

**Comment by cochcoder** [comment]
Ok, I'll make these changes

**Comment by cochcoder** [comment]
I have made all the changes and added a reason why you may want to add arc.msn.com back, which is as follows: "While arc.msn.com^$ctag=~device_pc|~os_windows removes Xbox One menu ads it also removes Game Pass benefits, so add at your own discretion!".

**Comment by cochcoder** [comment]
Should I remove the line "To add this copy and paste this on a new line: ||arc.msn.com^$ctag=~device_pc|~os_windows"?

**Comment by sefinek24** [comment]
Its ok

**Pull request merged**
